-- ══════════════════════════════════════════════════════════
-- V10: Set GIF URLs for V9 exercises (77/100 matched)
-- Source: ExerciseDB open-source library (static.exercisedb.dev)
-- Generated by scripts/match-exercise-gifs.ts
-- 23 exercises have no ExerciseDB equivalent — gif_url remains NULL
-- ══════════════════════════════════════════════════════════

-- CHEST
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/trqKQv2.gif' WHERE name = 'Smith Machine Bench Press';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/FVmZVhk.gif' WHERE name = 'Low Cable Fly';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/j7XMAyn.gif' WHERE name = 'High Cable Fly';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/jHAnWmT.gif' WHERE name = 'Incline Machine Press';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/DwhEmmE.gif' WHERE name = 'Decline Dumbbell Press';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/ESOd5Pl.gif' WHERE name = 'Incline Dumbbell Fly';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/5v7KYld.gif' WHERE name = 'Smith Machine Incline Press';

-- BACK
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/LEprlgG.gif' WHERE name = 'Wide Grip Lat Pulldown';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/qdRxqCj.gif' WHERE name = 'Close Grip Lat Pulldown';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/SzX3uzM.gif' WHERE name = 'Reverse Grip Barbell Row';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/x69MAlq.gif' WHERE name = 'Cable Pullover';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/9XjtHvS.gif' WHERE name = 'Dumbbell Pullover';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/JGKowMS.gif' WHERE name = 'Smith Machine Row';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/0V2YQjW.gif' WHERE name = 'Neutral Grip Pull Up';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/kiJ4Z2K.gif' WHERE name = 'Assisted Pull Up';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/za9Ni4z.gif' WHERE name = 'Rack Pull';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/XlZ4lAC.gif' WHERE name = 'Good Morning';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/bZGHsAZ.gif' WHERE name = 'Ring Row';

-- LEGS
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/jFtipLl.gif' WHERE name = 'Smith Machine Squat';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/t8iSghb.gif' WHERE name = 'Barbell Lunge';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/rR0LJzx.gif' WHERE name = 'Dumbbell Romanian Deadlift';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/aXtJhlg.gif' WHERE name = 'Step Up';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/C9LuR4A.gif' WHERE name = 'Donkey Calf Raise';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/bOOdeyc.gif' WHERE name = 'Seated Calf Raise';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/rR0LJzx.gif' WHERE name = 'Cable Romanian Deadlift';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/qKBpF7I.gif' WHERE name = 'Barbell Hip Thrust';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/qKBpF7I.gif' WHERE name = 'Dumbbell Hip Thrust';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/OM46QHm.gif' WHERE name = 'Cable Pull Through';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/py1HSzx.gif' WHERE name = 'Side Lunge';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/ykHcWme.gif' WHERE name = 'Leg Press Calf Raise';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/xdYPUtE.gif' WHERE name = 'Sissy Squat';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/pkSoCW9.gif' WHERE name = 'Jefferson Squat';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/oHsrypV.gif' WHERE name = 'Adductor Machine';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/CHpahtl.gif' WHERE name = 'Abductor Machine';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/qKBpF7I.gif' WHERE name = 'Glute Bridge';

-- SHOULDERS
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/DsgkuIt.gif' WHERE name = 'Dumbbell Lateral Raise';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/hxyTtWj.gif' WHERE name = 'Seated Dumbbell Lateral Raise';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/jjUPrze.gif' WHERE name = 'Smith Machine Overhead Press';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/FS63wTN.gif' WHERE name = 'Push Press';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/3eGE2JC.gif' WHERE name = 'Dumbbell Front Raise';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/u2X71Np.gif' WHERE name = 'Cable Front Raise';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/mu5Guxt.gif' WHERE name = 'Prone Rear Delt Raise';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/ainizkb.gif' WHERE name = 'Dumbbell Upright Row';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/cALKspW.gif' WHERE name = 'Cable Upright Row';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/eXMFHww.gif' WHERE name = 'Landmine Lateral Raise';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/5KLbZWx.gif' WHERE name = 'Kettlebell Overhead Press';

-- ARMS
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/h8LFzo9.gif' WHERE name = 'EZ Bar Skull Crusher';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/mpKZGWz.gif' WHERE name = 'Dumbbell Skull Crusher';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/HEJ6DIX.gif' WHERE name = 'Cable Tricep Kickback';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/dU605di.gif' WHERE name = 'Rope Pushdown';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/VjYliFZ.gif' WHERE name = 'Reverse Grip Pushdown';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/MU9HnE7.gif' WHERE name = 'Bench Dip';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/bZq4bwK.gif' WHERE name = 'Tricep Dip';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/xNrS20v.gif' WHERE name = 'Reverse Curl';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/82LxxkW.gif' WHERE name = 'Wrist Curl';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/IENzBdA.gif' WHERE name = 'Drag Curl';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/2kattbR.gif' WHERE name = 'Spider Curl';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/eHBlPsa.gif' WHERE name = 'Cable Preacher Curl';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/qRZ5S1N.gif' WHERE name = 'Single Arm Tricep Pushdown';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/kXaIn5A.gif' WHERE name = 'Zottman Curl';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/Qyk5J3p.gif' WHERE name = 'Cross Body Hammer Curl';

-- CORE
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/s8nrDXF.gif' WHERE name = 'Crunch';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/tZkGYZ9.gif' WHERE name = 'Bicycle Crunch';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/9pa4H5m.gif' WHERE name = 'Pallof Press';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/aVs3BR3.gif' WHERE name = 'Cable Woodchop High to Low';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/nCU1Ekp.gif' WHERE name = 'Reverse Crunch';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/QYysSLV.gif' WHERE name = 'Landmine Twist';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/8xUv4J7.gif' WHERE name = 'Cable Oblique Crunch';

-- FULL BODY
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/LHWF7us.gif' WHERE name = 'Kettlebell Clean';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/M74kdvm.gif' WHERE name = 'Kettlebell Snatch';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/iPm26QU.gif' WHERE name = 'Box Jump';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/oZjMu1t.gif' WHERE name = 'Tire Flip';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/Ha7SZ3y.gif' WHERE name = 'Turkish Get Up';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/RJgzwny.gif' WHERE name = 'Mountain Climber';

-- BACK (additional)
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/bZGHsAZ.gif' WHERE name = 'Inverted Row';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/wqNPGCg.gif' WHERE name = 'Cable Face Pull with Rotation';
UPDATE exercises SET gif_url = 'https://static.exercisedb.dev/media/jQGwmxN.gif' WHERE name = 'Trap Bar Deadlift';
