import { EquipmentType, ExerciseCategory, MuscleGroup, SpecificMuscle } from '../../types/exercise.types';

export type ExerciseSeed = {
    id: string;
    name: string;
    primaryMuscleGroup: MuscleGroup;
    primaryMuscles: SpecificMuscle[];
    secondaryMuscles?: SpecificMuscle[];
    equipment: EquipmentType;
    category: ExerciseCategory;
    idealRepsMin: number;
    idealRepsMax: number;
    isBilateral: boolean;
};

// Bump this when adding new exercises so existing users get seeded on next launch
export const EXPECTED_SEED_COUNT = 176;

export const DEFAULT_EXERCISES: ExerciseSeed[] = [

    // ── CHEST ──────────────────────────────────────────────────────────────
    {
        id: 'b8d9f1c4-2a1d-4e5c-9c3f-8a6b2d1f0e4a',
        name: 'Barbell Bench Press',
        primaryMuscleGroup: 'CHEST',
        primaryMuscles: ['MIDDLE_CHEST'],
        secondaryMuscles: ['FRONT_DELTS', 'TRICEPS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 3,
        idealRepsMax: 6,
        isBilateral: true,
    },
    {
        id: 'a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d',
        name: 'Dumbbell Bench Press',
        primaryMuscleGroup: 'CHEST',
        primaryMuscles: ['MIDDLE_CHEST', 'UPPER_CHEST'],
        secondaryMuscles: ['FRONT_DELTS', 'TRICEPS'],
        equipment: 'DUMBBELL',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e',
        name: 'Incline Barbell Press',
        primaryMuscleGroup: 'CHEST',
        primaryMuscles: ['UPPER_CHEST'],
        secondaryMuscles: ['FRONT_DELTS', 'TRICEPS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 5,
        idealRepsMax: 8,
        isBilateral: true,
    },
    {
        id: 'c3d4e5f6-a7b8-4c9d-ae1f-2a3b4c5d6e7f',
        name: 'Cable Fly',
        primaryMuscleGroup: 'CHEST',
        primaryMuscles: ['MIDDLE_CHEST'],
        secondaryMuscles: ['LOWER_CHEST'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'b6c7d8e9-f0a1-4b2c-8d3e-4f5a6b7c8d9e',
        name: 'Decline Barbell Press',
        primaryMuscleGroup: 'CHEST',
        primaryMuscles: ['LOWER_CHEST', 'MIDDLE_CHEST'],
        secondaryMuscles: ['TRICEPS', 'FRONT_DELTS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 6,
        idealRepsMax: 12,
        isBilateral: true,
    },
    {
        id: 'c7d8e9f0-a1b2-4c3d-9e4f-5a6b7c8d9e0f',
        name: 'Machine Chest Press',
        primaryMuscleGroup: 'CHEST',
        primaryMuscles: ['MIDDLE_CHEST', 'UPPER_CHEST'],
        secondaryMuscles: ['TRICEPS', 'FRONT_DELTS'],
        equipment: 'MACHINE',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'd8e9f0a1-b2c3-4d4e-ae5a-6b7c8d9e0f1a',
        name: 'Chest Dip',
        primaryMuscleGroup: 'CHEST',
        primaryMuscles: ['LOWER_CHEST', 'MIDDLE_CHEST'],
        secondaryMuscles: ['TRICEPS', 'FRONT_DELTS'],
        equipment: 'BODYWEIGHT',
        category: 'COMPOUND',
        idealRepsMin: 6,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'e9f0a1b2-c3d4-4e5f-bf6b-7c8d9e0f1a2b',
        name: 'Pec Deck',
        primaryMuscleGroup: 'CHEST',
        primaryMuscles: ['MIDDLE_CHEST'],
        secondaryMuscles: ['FRONT_DELTS'],
        equipment: 'MACHINE',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'f0a1b2c3-d4e5-4f6a-8c7c-8d9e0f1a2b3c',
        name: 'Cable Crossover',
        primaryMuscleGroup: 'CHEST',
        primaryMuscles: ['MIDDLE_CHEST', 'LOWER_CHEST'],
        secondaryMuscles: ['FRONT_DELTS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: true,
    },

    // ── BACK ───────────────────────────────────────────────────────────────

    {
        id: 'd4e5f6a7-b8c9-4d0e-8f2a-3b4c5d6e7f8a',
        name: 'Barbell Row',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['LATS', 'RHOMBOIDS'],
        secondaryMuscles: ['BICEPS', 'REAR_DELTS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 5,
        idealRepsMax: 8,
        isBilateral: true,
    },
    {
        id: 'e5f6a7b8-c9d0-4e1f-aa3b-4c5d6e7f8a9b',
        name: 'Pull Up',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['LATS'],
        secondaryMuscles: ['BICEPS', 'RHOMBOIDS'],
        equipment: 'BODYWEIGHT',
        category: 'COMPOUND',
        idealRepsMin: 5,
        idealRepsMax: 10,
        isBilateral: true,
    },
    {
        id: 'f6a7b8c9-d0e1-4f2a-bb4c-5d6e7f8a9b0c',
        name: 'Lat Pulldown',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['LATS'],
        secondaryMuscles: ['BICEPS', 'TRAPS'],
        equipment: 'CABLE',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 12,
        isBilateral: true,
    },
    {
        id: 'a7b8c9d0-e1f2-4a3b-8c5d-6e7f8a9b0c1d',
        name: 'Seated Cable Row',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['RHOMBOIDS', 'LATS'],
        secondaryMuscles: ['BICEPS'],
        equipment: 'CABLE',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 12,
        isBilateral: true,
    },
    {
        id: 'a1b2c3d4-e5f6-4a7b-9d8d-9e0f1a2b3c4d',
        name: 'One Arm Dumbbell Row',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['LATS', 'RHOMBOIDS'],
        secondaryMuscles: ['BICEPS', 'REAR_DELTS', 'TRAPS'],
        equipment: 'DUMBBELL',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: false,
    },
    {
        id: 'b2c3d4e5-f6a7-4b8c-ae9e-0f1a2b3c4d5e',
        name: 'T-Bar Row',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['LATS', 'RHOMBOIDS', 'TRAPS'],
        secondaryMuscles: ['BICEPS', 'REAR_DELTS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 6,
        idealRepsMax: 12,
        isBilateral: true,
    },
    {
        id: 'c3d4e5f6-a7b8-4c9d-bf0f-1a2b3c4d5e6f',
        name: 'Chest Supported Row',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['RHOMBOIDS', 'LATS', 'TRAPS'],
        secondaryMuscles: ['BICEPS', 'REAR_DELTS'],
        equipment: 'MACHINE',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'd4e5f6a7-b8c9-4d0e-8c1a-2b3c4d5e6f7a',
        name: 'Pendlay Row',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['LATS', 'RHOMBOIDS', 'TRAPS'],
        secondaryMuscles: ['BICEPS', 'REAR_DELTS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 4,
        idealRepsMax: 8,
        isBilateral: true,
    },
    {
        id: 'e5f6a7b8-c9d0-4e1f-9d2b-3c4d5e6f7a8b',
        name: 'Chin Up',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['LATS', 'RHOMBOIDS'],
        secondaryMuscles: ['BICEPS', 'REAR_DELTS'],
        equipment: 'BODYWEIGHT',
        category: 'COMPOUND',
        idealRepsMin: 4,
        idealRepsMax: 12,
        isBilateral: true,
    },
    {
        id: 'f6a7b8c9-d0e1-4f2a-ae3c-4d5e6f7a8b9c',
        name: 'Straight Arm Pulldown',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['LATS'],
        secondaryMuscles: ['TRICEPS', 'REAR_DELTS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a7b8c9d0-e1f2-4a3b-bf4d-5e6f7a8b9c0d',
        name: 'Hyperextension',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['LOWER_BACK', 'GLUTES'],
        secondaryMuscles: ['HAMSTRINGS'],
        equipment: 'BODYWEIGHT',
        category: 'COMPOUND',
        idealRepsMin: 10,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'b8c9d0e1-f2a3-4b4c-8c5e-6f7a8b9c0d1e',
        name: 'Single Arm Cable Row',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['RHOMBOIDS', 'LATS'],
        secondaryMuscles: ['BICEPS', 'REAR_DELTS'],
        equipment: 'CABLE',
        category: 'COMPOUND',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: false,
    },
    {
        id: 'c9d0e1f2-a3b4-4c5d-9d6f-7a8b9c0d1e2f',
        name: 'Machine Row',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['RHOMBOIDS', 'LATS', 'TRAPS'],
        secondaryMuscles: ['BICEPS', 'REAR_DELTS'],
        equipment: 'MACHINE',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },

    // ── LEGS ───────────────────────────────────────────────────────────────
    {
        id: 'd9e0f2d5-3b2e-5f6d-0d4g-9b7c3e2g1f5b',
        name: 'Barbell Squat',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['QUADS', 'GLUTES'],
        secondaryMuscles: ['HAMSTRINGS', 'LOWER_BACK', 'ABS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 3,
        idealRepsMax: 6,
        isBilateral: true,
    },
    {
        id: 'b8c9d0e1-f2a3-4b4c-9d6e-7f8a9b0c1d2e',
        name: 'Romanian Deadlift',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['HAMSTRINGS', 'GLUTES'],
        secondaryMuscles: ['LOWER_BACK'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 5,
        idealRepsMax: 8,
        isBilateral: true,
    },
    {
        id: 'c9d0e1f2-a3b4-4c5d-8e7f-8a9b0c1d2e3f',
        name: 'Leg Press',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['QUADS', 'GLUTES'],
        secondaryMuscles: ['HAMSTRINGS'],
        equipment: 'MACHINE',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 12,
        isBilateral: true,
    },
    {
        id: 'd0e1f2a3-b4c5-4d6e-bf8a-9b0c1d2e3f4a',
        name: 'Bulgarian Split Squat',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['QUADS', 'GLUTES'],
        secondaryMuscles: ['HAMSTRINGS'],
        equipment: 'DUMBBELL',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 12,
        isBilateral: false,
    },
    {
        id: 'e1f2a3b4-c5d6-4e7f-8a9b-0c1d2e3f4a5b',
        name: 'Leg Curl',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['HAMSTRINGS'],
        equipment: 'MACHINE',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'f2a3b4c5-d6e7-4f8a-9b0c-1d2e3f4a5b6c',
        name: 'Leg Extension',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['QUADS'],
        equipment: 'MACHINE',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a3b4c5d6-e7f8-4a9b-ac1d-2e3f4a5b6c7d',
        name: 'Calf Raise',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['CALVES'],
        equipment: 'MACHINE',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'd0e1f2a3-b4c5-4d6e-ae7a-8b9c0d1e2f3a',
        name: 'Front Squat',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['QUADS', 'GLUTES'],
        secondaryMuscles: ['ABS', 'LOWER_BACK'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 4,
        idealRepsMax: 8,
        isBilateral: true,
    },
    {
        id: 'e1f2a3b4-c5d6-4e7f-bf8b-9c0d1e2f3a4b',
        name: 'Goblet Squat',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['QUADS', 'GLUTES'],
        secondaryMuscles: ['ABS', 'HAMSTRINGS'],
        equipment: 'DUMBBELL',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'f2a3b4c5-d6e7-4f8a-8c9c-0d1e2f3a4b5c',
        name: 'Hack Squat',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['QUADS', 'GLUTES'],
        secondaryMuscles: ['HAMSTRINGS', 'CALVES'],
        equipment: 'MACHINE',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a3b4c5d6-e7f8-4a9b-9d0d-1e2f3a4b5c6d',
        name: 'Hip Thrust',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['GLUTES'],
        secondaryMuscles: ['HAMSTRINGS', 'QUADS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'b4c5d6e7-f8a9-4b0c-ae1e-2f3a4b5c6d7e',
        name: 'Sumo Deadlift',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['GLUTES', 'HAMSTRINGS', 'QUADS'],
        secondaryMuscles: ['LOWER_BACK', 'TRAPS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 3,
        idealRepsMax: 6,
        isBilateral: true,
    },
    {
        id: 'c5d6e7f8-a9b0-4c1d-bf2f-3a4b5c6d7e8f',
        name: 'Walking Lunge',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['QUADS', 'GLUTES'],
        secondaryMuscles: ['HAMSTRINGS', 'CALVES'],
        equipment: 'DUMBBELL',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 16,
        isBilateral: false,
    },
    {
        id: 'd6e7f8a9-b0c1-4d2e-8c3a-4b5c6d7e8f9a',
        name: 'Seated Leg Curl',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['HAMSTRINGS'],
        secondaryMuscles: ['GLUTES', 'CALVES'],
        equipment: 'MACHINE',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'e7f8a9b0-c1d2-4e3f-9d4b-5c6d7e8f9a0b',
        name: 'Standing Calf Raise',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['CALVES'],
        equipment: 'MACHINE',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'f8a9b0c1-d2e3-4f4a-ae5c-6d7e8f9a0b1c',
        name: 'Glute Kickback',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['GLUTES'],
        secondaryMuscles: ['HAMSTRINGS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: false,
    },

    // ── SHOULDERS ──────────────────────────────────────────────────────────
    {
        id: 'b4c5d6e7-f8a9-4b0c-8d2e-3f4a5b6c7d8e',
        name: 'Overhead Press',
        primaryMuscleGroup: 'SHOULDERS',
        primaryMuscles: ['FRONT_DELTS', 'SIDE_DELTS'],
        secondaryMuscles: ['TRICEPS', 'TRAPS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 4,
        idealRepsMax: 6,
        isBilateral: true,
    },
    {
        id: 'c5d6e7f8-a9b0-4c1d-ae3f-4a5b6c7d8e9f',
        name: 'Dumbbell Shoulder Press',
        primaryMuscleGroup: 'SHOULDERS',
        primaryMuscles: ['FRONT_DELTS', 'SIDE_DELTS'],
        secondaryMuscles: ['TRICEPS'],
        equipment: 'DUMBBELL',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 12,
        isBilateral: true,
    },

    {
        id: 'e7f8a9b0-c1d2-4e3f-8a5b-6c7d8e9f0a1b',
        name: 'Face Pull',
        primaryMuscleGroup: 'SHOULDERS',
        primaryMuscles: ['REAR_DELTS'],
        secondaryMuscles: ['RHOMBOIDS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a9b0c1d2-e3f4-4a5b-bf6d-7e8f9a0b1c2d',
        name: 'Arnold Press',
        primaryMuscleGroup: 'SHOULDERS',
        primaryMuscles: ['FRONT_DELTS', 'SIDE_DELTS'],
        secondaryMuscles: ['TRICEPS', 'REAR_DELTS'],
        equipment: 'DUMBBELL',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'b0c1d2e3-f4a5-4b6c-8c7e-8f9a0b1c2d3e',
        name: 'Machine Shoulder Press',
        primaryMuscleGroup: 'SHOULDERS',
        primaryMuscles: ['FRONT_DELTS', 'SIDE_DELTS'],
        secondaryMuscles: ['TRICEPS'],
        equipment: 'MACHINE',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'c1d2e3f4-a5b6-4c7d-9d8f-9a0b1c2d3e4f',
        name: 'Cable Lateral Raise',
        primaryMuscleGroup: 'SHOULDERS',
        primaryMuscles: ['SIDE_DELTS'],
        secondaryMuscles: ['TRAPS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: false,
    },
    {
        id: 'd2e3f4a5-b6c7-4d8e-ae9a-0b1c2d3e4f5a',
        name: 'Rear Delt Fly',
        primaryMuscleGroup: 'SHOULDERS',
        primaryMuscles: ['REAR_DELTS'],
        secondaryMuscles: ['RHOMBOIDS', 'TRAPS'],
        equipment: 'DUMBBELL',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'e3f4a5b6-c7d8-4e9f-bf0b-1c2d3e4f5a6b',
        name: 'Cable Rear Delt Fly',
        primaryMuscleGroup: 'SHOULDERS',
        primaryMuscles: ['REAR_DELTS'],
        secondaryMuscles: ['RHOMBOIDS', 'TRAPS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: false,
    },
    {
        id: 'f4a5b6c7-d8e9-4f0a-8c1c-2d3e4f5a6b7c',
        name: 'Barbell Shrug',
        primaryMuscleGroup: 'SHOULDERS',
        primaryMuscles: ['TRAPS'],
        secondaryMuscles: ['FOREARMS'],
        equipment: 'BARBELL',
        category: 'ISOLATION',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a5b6c7d8-e9f0-4a1b-9d2d-3e4f5a6b7c8d',
        name: 'Dumbbell Shrug',
        primaryMuscleGroup: 'SHOULDERS',
        primaryMuscles: ['TRAPS'],
        secondaryMuscles: ['FOREARMS'],
        equipment: 'DUMBBELL',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'b6c7d8e9-f0a1-4b2c-ae3e-4f5a6b7c8d9e',
        name: 'Upright Row',
        primaryMuscleGroup: 'SHOULDERS',
        primaryMuscles: ['SIDE_DELTS', 'TRAPS'],
        secondaryMuscles: ['BICEPS', 'FRONT_DELTS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },

    // ── ARMS ───────────────────────────────────────────────────────────────
    {
        id: 'f8a9b0c1-d2e3-4f4a-9b6c-7d8e9f0a1b2c',
        name: 'Barbell Curl',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['BICEPS'],
        secondaryMuscles: ['FOREARMS'],
        equipment: 'BARBELL',
        category: 'ISOLATION',
        idealRepsMin: 6,
        idealRepsMax: 10,
        isBilateral: true,
    },
    {
        id: 'a9b0c1d2-e3f4-4a5b-8c7d-8e9f0a1b2c3d',
        name: 'Dumbbell Curl',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['BICEPS'],
        secondaryMuscles: ['FOREARMS'],
        equipment: 'DUMBBELL',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: false,
    },
    {
        id: 'b0c1d2e3-f4a5-4b6c-8d8e-9f0a1b2c3d4e',
        name: 'Tricep Pushdown',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['TRICEPS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'c1d2e3f4-a5b6-4c7d-8e9f-0a1b2c3d4e5f',
        name: 'Skull Crusher',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['TRICEPS'],
        secondaryMuscles: ['FOREARMS'],
        equipment: 'BARBELL',
        category: 'ISOLATION',
        idealRepsMin: 6,
        idealRepsMax: 10,
        isBilateral: true,
    },
    {
        id: 'd2e3f4a5-b6c7-4d8e-9f0a-1b2c3d4e5f6a',
        name: 'Hammer Curl',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['BICEPS'],
        secondaryMuscles: ['FOREARMS'],
        equipment: 'DUMBBELL',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: false,
    },
    {
        id: 'c7d8e9f0-a1b2-4c3d-bf4f-5a6b7c8d9e0f',
        name: 'Cable Curl',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['BICEPS'],
        secondaryMuscles: ['FOREARMS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'd8e9f0a1-b2c3-4d4e-8c5a-6b7c8d9e0f1a',
        name: 'Preacher Curl',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['BICEPS'],
        secondaryMuscles: ['FOREARMS'],
        equipment: 'BARBELL',
        category: 'ISOLATION',
        idealRepsMin: 8,
        idealRepsMax: 12,
        isBilateral: true,
    },
    {
        id: 'e9f0a1b2-c3d4-4e5f-9d6b-7c8d9e0f1a2b',
        name: 'Incline Dumbbell Curl',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['BICEPS'],
        secondaryMuscles: ['FOREARMS'],
        equipment: 'DUMBBELL',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: false,
    },
    {
        id: 'f0a1b2c3-d4e5-4f6a-ae7c-8d9e0f1a2b3c',
        name: 'Concentration Curl',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['BICEPS'],
        secondaryMuscles: ['FOREARMS'],
        equipment: 'DUMBBELL',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: false,
    },
    {
        id: 'a1b2c3d4-e5f6-4a7b-bf8d-9e0f1a2b3c4d',
        name: 'Overhead Cable Tricep Extension',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['TRICEPS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'b2c3d4e5-f6a7-4b8c-8c9e-0f1a2b3c4d5e',
        name: 'Dumbbell Overhead Tricep Extension',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['TRICEPS'],
        equipment: 'DUMBBELL',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'c3d4e5f6-a7b8-4c9d-9d0f-1a2b3c4d5e6f',
        name: 'Tricep Kickback',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['TRICEPS'],
        equipment: 'DUMBBELL',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: false,
    },
    {
        id: 'd4e5f6a7-b8c9-4d0e-ae1a-2b3c4d5e6f7a',
        name: 'Close-Grip Bench Press',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['TRICEPS'],
        secondaryMuscles: ['MIDDLE_CHEST', 'FRONT_DELTS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 6,
        idealRepsMax: 12,
        isBilateral: true,
    },
    {
        id: 'e5f6a7b8-c9d0-4e1f-bf2b-3c4d5e6f7a8b',
        name: 'EZ Bar Curl',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['BICEPS'],
        secondaryMuscles: ['FOREARMS'],
        equipment: 'BARBELL',
        category: 'ISOLATION',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },

    // ── CORE ───────────────────────────────────────────────────────────────
    {
        id: 'e3f4a5b6-c7d8-4e9f-aa1b-2c3d4e5f6a7b',
        name: 'Plank',
        primaryMuscleGroup: 'CORE',
        primaryMuscles: ['ABS'],
        secondaryMuscles: ['OBLIQUES'],
        equipment: 'BODYWEIGHT',
        category: 'ISOLATION',
        idealRepsMin: 1,
        idealRepsMax: 1,
        isBilateral: true,
    },
    {
        id: 'f4a5b6c7-d8e9-4f0a-8b2c-3d4e5f6a7b8c',
        name: 'Cable Crunch',
        primaryMuscleGroup: 'CORE',
        primaryMuscles: ['ABS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 15,
        isBilateral: true,
    },

    {
        id: 'f6a7b8c9-d0e1-4f2a-8c3c-4d5e6f7a8b9c',
        name: 'Russian Twist',
        primaryMuscleGroup: 'CORE',
        primaryMuscles: ['OBLIQUES'],
        secondaryMuscles: ['ABS'],
        equipment: 'BODYWEIGHT',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a7b8c9d0-e1f2-4a3b-9d4d-5e6f7a8b9c0d',
        name: 'Side Plank',
        primaryMuscleGroup: 'CORE',
        primaryMuscles: ['OBLIQUES'],
        secondaryMuscles: ['ABS', 'LOWER_BACK'],
        equipment: 'BODYWEIGHT',
        category: 'ISOLATION',
        idealRepsMin: 1,
        idealRepsMax: 1,
        isBilateral: false,
    },
    {
        id: 'b8c9d0e1-f2a3-4b4c-ae5e-6f7a8b9c0d1e',
        name: 'Dead Bug',
        primaryMuscleGroup: 'CORE',
        primaryMuscles: ['ABS'],
        secondaryMuscles: ['OBLIQUES', 'LOWER_BACK'],
        equipment: 'BODYWEIGHT',
        category: 'ISOLATION',
        idealRepsMin: 8,
        idealRepsMax: 12,
        isBilateral: true,
    },
    {
        id: 'c9d0e1f2-a3b4-4c5d-bf6f-7a8b9c0d1e2f',
        name: 'Decline Sit Up',
        primaryMuscleGroup: 'CORE',
        primaryMuscles: ['ABS'],
        secondaryMuscles: ['HIP_FLEXORS'],
        equipment: 'BODYWEIGHT',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'd0e1f2a3-b4c5-4d6e-8c7a-8b9c0d1e2f3a',
        name: 'Wood Chop',
        primaryMuscleGroup: 'CORE',
        primaryMuscles: ['OBLIQUES'],
        secondaryMuscles: ['ABS', 'FRONT_DELTS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: false,
    },
    {
        id: 'e1f2a3b4-c5d6-4e7f-9d8b-9c0d1e2f3a4b',
        name: 'Leg Raise',
        primaryMuscleGroup: 'CORE',
        primaryMuscles: ['ABS', 'HIP_FLEXORS'],
        secondaryMuscles: ['OBLIQUES'],
        equipment: 'BODYWEIGHT',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 20,
        isBilateral: true,
    },

    // ── FULL BODY ──────────────────────────────────────────────────────────
    {
        id: 'f2a3b4c5-d6e7-4f8a-ae9c-0d1e2f3a4b5c',
        name: 'Kettlebell Swing',
        primaryMuscleGroup: 'FULL_BODY',
        primaryMuscles: ['GLUTES', 'HAMSTRINGS'],
        secondaryMuscles: ['LOWER_BACK', 'TRAPS', 'ABS'],
        equipment: 'KETTLEBELL',
        category: 'COMPOUND',
        idealRepsMin: 10,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a3b4c5d6-e7f8-4a9b-bf0d-1e2f3a4b5c6d',
        name: "Farmer's Walk",
        primaryMuscleGroup: 'FULL_BODY',
        primaryMuscles: ['TRAPS', 'FOREARMS'],
        secondaryMuscles: ['ABS', 'GLUTES', 'CALVES'],
        equipment: 'DUMBBELL',
        category: 'COMPOUND',
        idealRepsMin: 1,
        idealRepsMax: 1,
        isBilateral: true,
    },
    {
        id: 'b4c5d6e7-f8a9-4b0c-8c1e-2f3a4b5c6d7e',
        name: 'Thruster',
        primaryMuscleGroup: 'FULL_BODY',
        primaryMuscles: ['QUADS', 'FRONT_DELTS', 'GLUTES'],
        secondaryMuscles: ['TRICEPS', 'ABS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 5,
        idealRepsMax: 10,
        isBilateral: true,
    },
    {
        id: 'c5d6e7f8-a9b0-4c1d-9d2f-3a4b5c6d7e8f',
        name: 'Barbell Clean and Press',
        primaryMuscleGroup: 'FULL_BODY',
        primaryMuscles: ['TRAPS', 'QUADS', 'FRONT_DELTS'],
        secondaryMuscles: ['GLUTES', 'HAMSTRINGS', 'TRICEPS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 3,
        idealRepsMax: 6,
        isBilateral: true,
    },
    {
        id: 'd6e7f8a9-b0c1-4d2e-ae3a-4b5c6d7e8f9a',
        name: 'Burpee',
        primaryMuscleGroup: 'FULL_BODY',
        primaryMuscles: ['QUADS', 'MIDDLE_CHEST', 'GLUTES'],
        secondaryMuscles: ['ABS', 'TRICEPS', 'CALVES'],
        equipment: 'BODYWEIGHT',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 20,
        isBilateral: true,
    },
    // ── CHEST (new) ───────────────────────────────────────────────────────
    {
        id: 'a2000000-0000-0000-0000-000000000001',
        name: 'Smith Machine Bench Press',
        primaryMuscleGroup: 'CHEST',
        primaryMuscles: ['MIDDLE_CHEST', 'UPPER_CHEST'],
        secondaryMuscles: ['TRICEPS', 'FRONT_DELTS'],
        equipment: 'SMITH_MACHINE',
        category: 'COMPOUND',
        idealRepsMin: 6,
        idealRepsMax: 12,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000002',
        name: 'Low Cable Fly',
        primaryMuscleGroup: 'CHEST',
        primaryMuscles: ['LOWER_CHEST'],
        secondaryMuscles: ['MIDDLE_CHEST', 'FRONT_DELTS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000003',
        name: 'High Cable Fly',
        primaryMuscleGroup: 'CHEST',
        primaryMuscles: ['UPPER_CHEST'],
        secondaryMuscles: ['MIDDLE_CHEST', 'FRONT_DELTS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000004',
        name: 'Incline Machine Press',
        primaryMuscleGroup: 'CHEST',
        primaryMuscles: ['UPPER_CHEST'],
        secondaryMuscles: ['TRICEPS', 'FRONT_DELTS'],
        equipment: 'MACHINE',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000005',
        name: 'Decline Dumbbell Press',
        primaryMuscleGroup: 'CHEST',
        primaryMuscles: ['LOWER_CHEST', 'MIDDLE_CHEST'],
        secondaryMuscles: ['TRICEPS', 'FRONT_DELTS'],
        equipment: 'DUMBBELL',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000006',
        name: 'Incline Dumbbell Fly',
        primaryMuscleGroup: 'CHEST',
        primaryMuscles: ['UPPER_CHEST'],
        secondaryMuscles: ['FRONT_DELTS'],
        equipment: 'DUMBBELL',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000007',
        name: 'Smith Machine Incline Press',
        primaryMuscleGroup: 'CHEST',
        primaryMuscles: ['UPPER_CHEST'],
        secondaryMuscles: ['TRICEPS', 'FRONT_DELTS'],
        equipment: 'SMITH_MACHINE',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 12,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000008',
        name: 'Landmine Press',
        primaryMuscleGroup: 'CHEST',
        primaryMuscles: ['UPPER_CHEST', 'FRONT_DELTS'],
        secondaryMuscles: ['TRICEPS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: false,
    },

    // ── BACK (new) ───────────────────────────────────────────────────────────
    {
        id: 'a2000000-0000-0000-0000-000000000009',
        name: 'Wide Grip Lat Pulldown',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['LATS'],
        secondaryMuscles: ['BICEPS', 'REAR_DELTS'],
        equipment: 'CABLE',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000010',
        name: 'Close Grip Lat Pulldown',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['LATS'],
        secondaryMuscles: ['BICEPS', 'RHOMBOIDS'],
        equipment: 'CABLE',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000011',
        name: 'Reverse Grip Barbell Row',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['LATS', 'RHOMBOIDS'],
        secondaryMuscles: ['BICEPS', 'REAR_DELTS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 6,
        idealRepsMax: 12,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000012',
        name: 'Meadows Row',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['LATS', 'RHOMBOIDS'],
        secondaryMuscles: ['BICEPS', 'REAR_DELTS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 12,
        isBilateral: false,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000013',
        name: 'Cable Pullover',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['LATS'],
        secondaryMuscles: ['TRICEPS', 'REAR_DELTS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000014',
        name: 'Dumbbell Pullover',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['LATS'],
        secondaryMuscles: ['TRICEPS'],
        equipment: 'DUMBBELL',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000015',
        name: 'Smith Machine Row',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['RHOMBOIDS', 'LATS', 'TRAPS'],
        secondaryMuscles: ['BICEPS', 'REAR_DELTS'],
        equipment: 'SMITH_MACHINE',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000016',
        name: 'Neutral Grip Pull Up',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['LATS', 'BICEPS'],
        secondaryMuscles: ['RHOMBOIDS', 'REAR_DELTS'],
        equipment: 'BODYWEIGHT',
        category: 'COMPOUND',
        idealRepsMin: 4,
        idealRepsMax: 12,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000017',
        name: 'Assisted Pull Up',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['LATS'],
        secondaryMuscles: ['BICEPS', 'RHOMBOIDS'],
        equipment: 'MACHINE',
        category: 'COMPOUND',
        idealRepsMin: 6,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000018',
        name: 'Rack Pull',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['TRAPS', 'LOWER_BACK', 'LATS'],
        secondaryMuscles: ['GLUTES', 'HAMSTRINGS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 3,
        idealRepsMax: 6,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000019',
        name: 'Good Morning',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['LOWER_BACK', 'HAMSTRINGS'],
        secondaryMuscles: ['GLUTES', 'ABS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000020',
        name: 'Ring Row',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['RHOMBOIDS', 'LATS'],
        secondaryMuscles: ['BICEPS', 'REAR_DELTS'],
        equipment: 'BODYWEIGHT',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000093',
        name: 'Band Pull Apart',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['REAR_DELTS', 'RHOMBOIDS'],
        secondaryMuscles: ['TRAPS'],
        equipment: 'OTHER',
        category: 'ISOLATION',
        idealRepsMin: 15,
        idealRepsMax: 30,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000094',
        name: 'Inverted Row',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['RHOMBOIDS', 'LATS'],
        secondaryMuscles: ['BICEPS', 'REAR_DELTS'],
        equipment: 'BODYWEIGHT',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000095',
        name: 'Cable Face Pull with Rotation',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['REAR_DELTS', 'TRAPS'],
        secondaryMuscles: ['RHOMBOIDS', 'BICEPS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000096',
        name: 'Trap Bar Deadlift',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['LOWER_BACK', 'TRAPS', 'LATS'],
        secondaryMuscles: ['GLUTES', 'HAMSTRINGS', 'QUADS'],
        equipment: 'OTHER',
        category: 'COMPOUND',
        idealRepsMin: 3,
        idealRepsMax: 6,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000097',
        name: 'Seal Row',
        primaryMuscleGroup: 'BACK',
        primaryMuscles: ['RHOMBOIDS', 'LATS'],
        secondaryMuscles: ['BICEPS', 'REAR_DELTS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },

    // ── LEGS (new) ───────────────────────────────────────────────────────────
    {
        id: 'a2000000-0000-0000-0000-000000000021',
        name: 'Smith Machine Squat',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['QUADS', 'GLUTES'],
        secondaryMuscles: ['HAMSTRINGS', 'LOWER_BACK'],
        equipment: 'SMITH_MACHINE',
        category: 'COMPOUND',
        idealRepsMin: 6,
        idealRepsMax: 12,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000022',
        name: 'Barbell Lunge',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['QUADS', 'GLUTES'],
        secondaryMuscles: ['HAMSTRINGS', 'CALVES'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 12,
        isBilateral: false,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000023',
        name: 'Dumbbell Romanian Deadlift',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['HAMSTRINGS', 'GLUTES'],
        secondaryMuscles: ['LOWER_BACK', 'CALVES'],
        equipment: 'DUMBBELL',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000024',
        name: 'Step Up',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['QUADS', 'GLUTES'],
        secondaryMuscles: ['HAMSTRINGS', 'CALVES'],
        equipment: 'DUMBBELL',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: false,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000025',
        name: 'Box Squat',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['QUADS', 'GLUTES'],
        secondaryMuscles: ['HAMSTRINGS', 'LOWER_BACK'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 3,
        idealRepsMax: 6,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000026',
        name: 'Nordic Hamstring Curl',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['HAMSTRINGS'],
        secondaryMuscles: ['GLUTES', 'CALVES'],
        equipment: 'BODYWEIGHT',
        category: 'ISOLATION',
        idealRepsMin: 3,
        idealRepsMax: 8,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000027',
        name: 'Donkey Calf Raise',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['CALVES'],
        equipment: 'MACHINE',
        category: 'ISOLATION',
        idealRepsMin: 15,
        idealRepsMax: 25,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000028',
        name: 'Seated Calf Raise',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['CALVES'],
        equipment: 'MACHINE',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000029',
        name: 'Cable Romanian Deadlift',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['HAMSTRINGS', 'GLUTES'],
        secondaryMuscles: ['LOWER_BACK'],
        equipment: 'CABLE',
        category: 'COMPOUND',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000030',
        name: 'Single Leg Press',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['QUADS', 'GLUTES'],
        secondaryMuscles: ['HAMSTRINGS', 'CALVES'],
        equipment: 'MACHINE',
        category: 'COMPOUND',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: false,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000031',
        name: 'Barbell Hip Thrust',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['GLUTES'],
        secondaryMuscles: ['HAMSTRINGS', 'QUADS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000032',
        name: 'Dumbbell Hip Thrust',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['GLUTES'],
        secondaryMuscles: ['HAMSTRINGS', 'QUADS'],
        equipment: 'DUMBBELL',
        category: 'COMPOUND',
        idealRepsMin: 10,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000033',
        name: 'Cable Pull Through',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['GLUTES', 'HAMSTRINGS'],
        secondaryMuscles: ['LOWER_BACK'],
        equipment: 'CABLE',
        category: 'COMPOUND',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000034',
        name: 'Reverse Lunge',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['QUADS', 'GLUTES'],
        secondaryMuscles: ['HAMSTRINGS', 'CALVES'],
        equipment: 'DUMBBELL',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: false,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000035',
        name: 'Side Lunge',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['QUADS', 'GLUTES'],
        secondaryMuscles: ['HAMSTRINGS'],
        equipment: 'DUMBBELL',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: false,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000036',
        name: 'Leg Press Calf Raise',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['CALVES'],
        equipment: 'MACHINE',
        category: 'ISOLATION',
        idealRepsMin: 15,
        idealRepsMax: 25,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000037',
        name: 'Sissy Squat',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['QUADS'],
        secondaryMuscles: ['CALVES'],
        equipment: 'BODYWEIGHT',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000038',
        name: 'Jefferson Squat',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['QUADS', 'GLUTES', 'HAMSTRINGS'],
        secondaryMuscles: ['LOWER_BACK', 'ABS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 4,
        idealRepsMax: 8,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000098',
        name: 'Adductor Machine',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['GLUTES'],
        secondaryMuscles: ['GLUTES'],
        equipment: 'MACHINE',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000099',
        name: 'Abductor Machine',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['GLUTES'],
        equipment: 'MACHINE',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000100',
        name: 'Glute Bridge',
        primaryMuscleGroup: 'LEGS',
        primaryMuscles: ['GLUTES'],
        secondaryMuscles: ['HAMSTRINGS', 'LOWER_BACK'],
        equipment: 'BODYWEIGHT',
        category: 'COMPOUND',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: true,
    },

    // ── SHOULDERS (new) ──────────────────────────────────────────────────────
    {
        id: 'a2000000-0000-0000-0000-000000000039',
        name: 'Dumbbell Lateral Raise',
        primaryMuscleGroup: 'SHOULDERS',
        primaryMuscles: ['SIDE_DELTS'],
        secondaryMuscles: ['TRAPS'],
        equipment: 'DUMBBELL',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000040',
        name: 'Seated Dumbbell Lateral Raise',
        primaryMuscleGroup: 'SHOULDERS',
        primaryMuscles: ['SIDE_DELTS'],
        secondaryMuscles: ['TRAPS'],
        equipment: 'DUMBBELL',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000041',
        name: 'Smith Machine Overhead Press',
        primaryMuscleGroup: 'SHOULDERS',
        primaryMuscles: ['FRONT_DELTS', 'SIDE_DELTS'],
        secondaryMuscles: ['TRICEPS', 'TRAPS'],
        equipment: 'SMITH_MACHINE',
        category: 'COMPOUND',
        idealRepsMin: 6,
        idealRepsMax: 12,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000042',
        name: 'Push Press',
        primaryMuscleGroup: 'SHOULDERS',
        primaryMuscles: ['FRONT_DELTS', 'SIDE_DELTS'],
        secondaryMuscles: ['TRICEPS', 'TRAPS', 'QUADS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 3,
        idealRepsMax: 6,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000043',
        name: 'Plate Front Raise',
        primaryMuscleGroup: 'SHOULDERS',
        primaryMuscles: ['FRONT_DELTS'],
        secondaryMuscles: ['SIDE_DELTS'],
        equipment: 'OTHER',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000044',
        name: 'Dumbbell Front Raise',
        primaryMuscleGroup: 'SHOULDERS',
        primaryMuscles: ['FRONT_DELTS'],
        secondaryMuscles: ['SIDE_DELTS'],
        equipment: 'DUMBBELL',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000045',
        name: 'Cable Front Raise',
        primaryMuscleGroup: 'SHOULDERS',
        primaryMuscles: ['FRONT_DELTS'],
        secondaryMuscles: ['SIDE_DELTS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000046',
        name: 'Prone Rear Delt Raise',
        primaryMuscleGroup: 'SHOULDERS',
        primaryMuscles: ['REAR_DELTS'],
        secondaryMuscles: ['RHOMBOIDS', 'TRAPS'],
        equipment: 'DUMBBELL',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000047',
        name: 'Dumbbell Upright Row',
        primaryMuscleGroup: 'SHOULDERS',
        primaryMuscles: ['SIDE_DELTS', 'TRAPS'],
        secondaryMuscles: ['BICEPS'],
        equipment: 'DUMBBELL',
        category: 'COMPOUND',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000048',
        name: 'Cable Upright Row',
        primaryMuscleGroup: 'SHOULDERS',
        primaryMuscles: ['SIDE_DELTS', 'TRAPS'],
        secondaryMuscles: ['BICEPS'],
        equipment: 'CABLE',
        category: 'COMPOUND',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000049',
        name: 'Landmine Lateral Raise',
        primaryMuscleGroup: 'SHOULDERS',
        primaryMuscles: ['SIDE_DELTS'],
        secondaryMuscles: ['TRAPS', 'FRONT_DELTS'],
        equipment: 'BARBELL',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 20,
        isBilateral: false,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000050',
        name: 'Kettlebell Overhead Press',
        primaryMuscleGroup: 'SHOULDERS',
        primaryMuscles: ['FRONT_DELTS', 'SIDE_DELTS'],
        secondaryMuscles: ['TRICEPS', 'TRAPS'],
        equipment: 'KETTLEBELL',
        category: 'COMPOUND',
        idealRepsMin: 6,
        idealRepsMax: 12,
        isBilateral: false,
    },

    // ── ARMS (new) ───────────────────────────────────────────────────────────
    {
        id: 'a2000000-0000-0000-0000-000000000051',
        name: 'EZ Bar Skull Crusher',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['TRICEPS'],
        equipment: 'BARBELL',
        category: 'ISOLATION',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000052',
        name: 'Dumbbell Skull Crusher',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['TRICEPS'],
        equipment: 'DUMBBELL',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000053',
        name: 'Cable Tricep Kickback',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['TRICEPS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: false,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000054',
        name: 'Rope Pushdown',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['TRICEPS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000055',
        name: 'Reverse Grip Pushdown',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['TRICEPS'],
        secondaryMuscles: ['FOREARMS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000056',
        name: 'Bench Dip',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['TRICEPS'],
        secondaryMuscles: ['FRONT_DELTS'],
        equipment: 'BODYWEIGHT',
        category: 'ISOLATION',
        idealRepsMin: 8,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000057',
        name: 'Tricep Dip',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['TRICEPS'],
        secondaryMuscles: ['FRONT_DELTS'],
        equipment: 'BODYWEIGHT',
        category: 'COMPOUND',
        idealRepsMin: 5,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000058',
        name: 'Reverse Curl',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['FOREARMS', 'BICEPS'],
        equipment: 'BARBELL',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000059',
        name: 'Wrist Curl',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['FOREARMS'],
        equipment: 'BARBELL',
        category: 'ISOLATION',
        idealRepsMin: 15,
        idealRepsMax: 25,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000060',
        name: 'Dumbbell Wrist Curl',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['FOREARMS'],
        equipment: 'DUMBBELL',
        category: 'ISOLATION',
        idealRepsMin: 15,
        idealRepsMax: 25,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000061',
        name: 'Drag Curl',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['BICEPS'],
        secondaryMuscles: ['FOREARMS'],
        equipment: 'BARBELL',
        category: 'ISOLATION',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000062',
        name: 'Spider Curl',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['BICEPS'],
        secondaryMuscles: ['FOREARMS'],
        equipment: 'BARBELL',
        category: 'ISOLATION',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000063',
        name: 'Cable Preacher Curl',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['BICEPS'],
        secondaryMuscles: ['FOREARMS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000064',
        name: 'Single Arm Tricep Pushdown',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['TRICEPS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 20,
        isBilateral: false,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000065',
        name: 'Zottman Curl',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['BICEPS', 'FOREARMS'],
        equipment: 'DUMBBELL',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: false,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000066',
        name: 'Cross Body Hammer Curl',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['BICEPS', 'FOREARMS'],
        equipment: 'DUMBBELL',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: false,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000067',
        name: 'Bayesian Curl',
        primaryMuscleGroup: 'ARMS',
        primaryMuscles: ['BICEPS'],
        secondaryMuscles: ['FOREARMS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: false,
    },

    // ── CORE (new) ───────────────────────────────────────────────────────────
    {
        id: 'a2000000-0000-0000-0000-000000000068',
        name: 'Crunch',
        primaryMuscleGroup: 'CORE',
        primaryMuscles: ['ABS'],
        secondaryMuscles: ['OBLIQUES'],
        equipment: 'BODYWEIGHT',
        category: 'ISOLATION',
        idealRepsMin: 15,
        idealRepsMax: 30,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000069',
        name: 'Bicycle Crunch',
        primaryMuscleGroup: 'CORE',
        primaryMuscles: ['ABS', 'OBLIQUES'],
        equipment: 'BODYWEIGHT',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 25,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000070',
        name: 'Dragon Flag',
        primaryMuscleGroup: 'CORE',
        primaryMuscles: ['ABS'],
        secondaryMuscles: ['OBLIQUES', 'HIP_FLEXORS'],
        equipment: 'BODYWEIGHT',
        category: 'ISOLATION',
        idealRepsMin: 5,
        idealRepsMax: 10,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000071',
        name: 'Pallof Press',
        primaryMuscleGroup: 'CORE',
        primaryMuscles: ['ABS', 'OBLIQUES'],
        secondaryMuscles: ['LOWER_BACK'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: false,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000072',
        name: 'Cable Woodchop High to Low',
        primaryMuscleGroup: 'CORE',
        primaryMuscles: ['OBLIQUES'],
        secondaryMuscles: ['ABS', 'FRONT_DELTS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 15,
        isBilateral: false,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000073',
        name: 'Reverse Crunch',
        primaryMuscleGroup: 'CORE',
        primaryMuscles: ['ABS', 'HIP_FLEXORS'],
        secondaryMuscles: ['OBLIQUES'],
        equipment: 'BODYWEIGHT',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000074',
        name: 'Landmine Twist',
        primaryMuscleGroup: 'CORE',
        primaryMuscles: ['OBLIQUES'],
        secondaryMuscles: ['ABS', 'FRONT_DELTS'],
        equipment: 'BARBELL',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000075',
        name: 'Hollow Body Hold',
        primaryMuscleGroup: 'CORE',
        primaryMuscles: ['ABS'],
        secondaryMuscles: ['HIP_FLEXORS', 'LOWER_BACK'],
        equipment: 'BODYWEIGHT',
        category: 'ISOLATION',
        idealRepsMin: 1,
        idealRepsMax: 1,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000076',
        name: 'V-Up',
        primaryMuscleGroup: 'CORE',
        primaryMuscles: ['ABS', 'HIP_FLEXORS'],
        secondaryMuscles: ['OBLIQUES'],
        equipment: 'BODYWEIGHT',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000077',
        name: 'Toes To Bar',
        primaryMuscleGroup: 'CORE',
        primaryMuscles: ['ABS', 'HIP_FLEXORS'],
        secondaryMuscles: ['OBLIQUES'],
        equipment: 'BODYWEIGHT',
        category: 'ISOLATION',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000078',
        name: 'Weighted Sit Up',
        primaryMuscleGroup: 'CORE',
        primaryMuscles: ['ABS'],
        secondaryMuscles: ['HIP_FLEXORS', 'OBLIQUES'],
        equipment: 'OTHER',
        category: 'ISOLATION',
        idealRepsMin: 10,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000079',
        name: 'Cable Oblique Crunch',
        primaryMuscleGroup: 'CORE',
        primaryMuscles: ['OBLIQUES'],
        secondaryMuscles: ['ABS'],
        equipment: 'CABLE',
        category: 'ISOLATION',
        idealRepsMin: 12,
        idealRepsMax: 20,
        isBilateral: false,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000080',
        name: 'Plank Hip Dip',
        primaryMuscleGroup: 'CORE',
        primaryMuscles: ['OBLIQUES', 'ABS'],
        secondaryMuscles: ['LOWER_BACK'],
        equipment: 'BODYWEIGHT',
        category: 'ISOLATION',
        idealRepsMin: 15,
        idealRepsMax: 30,
        isBilateral: true,
    },

    // ── FULL BODY (new) ──────────────────────────────────────────────────────
    {
        id: 'a2000000-0000-0000-0000-000000000081',
        name: 'Kettlebell Clean',
        primaryMuscleGroup: 'FULL_BODY',
        primaryMuscles: ['TRAPS', 'GLUTES', 'QUADS'],
        secondaryMuscles: ['HAMSTRINGS', 'CALVES', 'FRONT_DELTS'],
        equipment: 'KETTLEBELL',
        category: 'COMPOUND',
        idealRepsMin: 5,
        idealRepsMax: 10,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000082',
        name: 'Kettlebell Snatch',
        primaryMuscleGroup: 'FULL_BODY',
        primaryMuscles: ['TRAPS', 'GLUTES', 'FRONT_DELTS'],
        secondaryMuscles: ['HAMSTRINGS', 'ABS'],
        equipment: 'KETTLEBELL',
        category: 'COMPOUND',
        idealRepsMin: 3,
        idealRepsMax: 8,
        isBilateral: false,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000083',
        name: 'Box Jump',
        primaryMuscleGroup: 'FULL_BODY',
        primaryMuscles: ['QUADS', 'GLUTES'],
        secondaryMuscles: ['HAMSTRINGS', 'CALVES'],
        equipment: 'BODYWEIGHT',
        category: 'COMPOUND',
        idealRepsMin: 5,
        idealRepsMax: 10,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000084',
        name: 'Broad Jump',
        primaryMuscleGroup: 'FULL_BODY',
        primaryMuscles: ['QUADS', 'GLUTES'],
        secondaryMuscles: ['HAMSTRINGS', 'CALVES'],
        equipment: 'BODYWEIGHT',
        category: 'COMPOUND',
        idealRepsMin: 5,
        idealRepsMax: 8,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000085',
        name: 'Wall Ball',
        primaryMuscleGroup: 'FULL_BODY',
        primaryMuscles: ['QUADS', 'GLUTES', 'FRONT_DELTS'],
        secondaryMuscles: ['TRICEPS', 'ABS'],
        equipment: 'OTHER',
        category: 'COMPOUND',
        idealRepsMin: 10,
        idealRepsMax: 20,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000086',
        name: 'Battle Rope Waves',
        primaryMuscleGroup: 'FULL_BODY',
        primaryMuscles: ['FRONT_DELTS', 'TRAPS'],
        secondaryMuscles: ['ABS', 'FOREARMS'],
        equipment: 'OTHER',
        category: 'COMPOUND',
        idealRepsMin: 1,
        idealRepsMax: 1,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000087',
        name: 'Sled Push',
        primaryMuscleGroup: 'FULL_BODY',
        primaryMuscles: ['QUADS', 'GLUTES'],
        secondaryMuscles: ['HAMSTRINGS', 'CALVES', 'ABS'],
        equipment: 'OTHER',
        category: 'COMPOUND',
        idealRepsMin: 1,
        idealRepsMax: 1,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000088',
        name: 'Tire Flip',
        primaryMuscleGroup: 'FULL_BODY',
        primaryMuscles: ['GLUTES', 'QUADS', 'TRAPS'],
        secondaryMuscles: ['HAMSTRINGS', 'LOWER_BACK'],
        equipment: 'OTHER',
        category: 'COMPOUND',
        idealRepsMin: 5,
        idealRepsMax: 10,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000089',
        name: 'Turkish Get Up',
        primaryMuscleGroup: 'FULL_BODY',
        primaryMuscles: ['GLUTES', 'ABS', 'FRONT_DELTS'],
        secondaryMuscles: ['TRICEPS', 'LOWER_BACK'],
        equipment: 'KETTLEBELL',
        category: 'COMPOUND',
        idealRepsMin: 3,
        idealRepsMax: 6,
        isBilateral: false,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000090',
        name: 'Barbell Complex',
        primaryMuscleGroup: 'FULL_BODY',
        primaryMuscles: ['QUADS', 'TRAPS', 'GLUTES'],
        secondaryMuscles: ['HAMSTRINGS', 'FRONT_DELTS', 'ABS'],
        equipment: 'BARBELL',
        category: 'COMPOUND',
        idealRepsMin: 5,
        idealRepsMax: 8,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000091',
        name: 'Dumbbell Thruster',
        primaryMuscleGroup: 'FULL_BODY',
        primaryMuscles: ['QUADS', 'FRONT_DELTS', 'GLUTES'],
        secondaryMuscles: ['TRICEPS', 'ABS'],
        equipment: 'DUMBBELL',
        category: 'COMPOUND',
        idealRepsMin: 8,
        idealRepsMax: 15,
        isBilateral: true,
    },
    {
        id: 'a2000000-0000-0000-0000-000000000092',
        name: 'Mountain Climber',
        primaryMuscleGroup: 'FULL_BODY',
        primaryMuscles: ['ABS', 'HIP_FLEXORS'],
        secondaryMuscles: ['QUADS', 'FRONT_DELTS'],
        equipment: 'BODYWEIGHT',
        category: 'COMPOUND',
        idealRepsMin: 10,
        idealRepsMax: 30,
        isBilateral: true,
    },
];
